export enum ENDPOINT {
    LOGIN = "auth/login",
    REGISTER = "auth/register",
    ME = "auth/me",
    BILLING = "me/billing",
    NOTIFICATIONS = "me/notifications",
    POST = "posts",
    MINE_POST = "me/posts",
    LIKE_POST = "posts/like",
    COMMENT_POST = "posts/comment",
    TOKEN_POST = "posts/token",
    FEED_GENERATE = "generate/feed",
    IMAGE_GENERATE = "generate/image",
    POST_GENERATE = 'generate/feed/post',
    IMAGE_POST = 'generate/image/post',
    SEARCH = "search",
}