export enum ENDPOINT {
    LOGIN = "auth/login",
    REGISTER = "auth/register",
    ME = "auth/me",
    BILLING = "me/billing",
    NOTIFICATIONS = "me/notifications",
    POST = "posts",
    MINE_POST = "me/posts",
    LIKE_POST = "posts/like",
    COMMENT_POST = "posts/comment",
    TROPHY_POST = "posts/trophy",
    FEED_GENERATE = "generate/feed",
    IMAGE_GENERATE = "generate/image",
    POST_GENERATE = 'generate/feed/post',
    IMAGE_POST = 'generate/image/post',
    SEARCH = "search",
    UPLOAD_IMAGE = "upload/image",
    UPLOAD_VIDEO = "upload/video",
    CREATE_PAYMENT_INTENT="create_payment_intent",
    UPDATE_PAYMENT_INTENT="update_payment_intent",
    COMPLETE_PAYMENT="complete_payment",
    IMAGE_EDIT="generate/edit/image",

    UPDATE_PASSWORD="auth/update-password",
    UPDATE_DETAIL="auth/update-detail",
    UPDATE_PROFILE="auth/update-profile"
}